apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  namespace: dev
  replicas: 8
  selector:
    matchlabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: c1
          image: nginx
          ports:
            - containerport: 8080
